### ISSUE TITLE
Ship Names randomly not showing in game

### ISSUE THREAD

**Issue by deshah10** [daud-io/daud#127]
Several times now I have experienced, where the game just doesnt show any enemy ship names.. I am not sure what causes the bug, but I suspect it is caused from switching to a differenct arena.. I just faced this issue again, after switching to the Duel Room, and then going back to FFA (US), names were dissapeared on FFA (US).

**Comment by andylippitt** [comment]
what are your settings for:
show names
show your name
name size

**Comment by deshah10** [comment]
SETTINGS FOR:
show Name = true
show Own Names = true
(Always has been default)

Name is "Des"

**Comment by andylippitt** [comment]
did you check for console errors when it happens? also note if there's a drop in fps.

**Comment by deshah10** [comment]
fps was normal, but yeah I dont remember seeing any console errors either.. Will look out on conso next time it happens
