### ISSUE TITLE
Emoji picker issues & suggestions

### ISSUE THREAD

**Issue by deshah10** [daud-io/daud#128]
Emoji Picker is currently forced to a user, instead of allowing the user to choose when and where they want to insert emojis for there nickname. 

- The space that the emoji currently takes is not accounted for on the nickname box, resulting in excess nickname text being cutoff

- For the way the current emoji picker behaves it would be good if it could remember your last picked emoji as currently when you re open your browser the selected emoji gets forgotten.

- Possibly include a rencently/ previously used emoji section, on the picker to make it easier to find emojis you regularly use.

- Make emoji picker window close when you click anywhere out side of its window.

**Comment by andylippitt** [comment]
Des... there's another branch that had a rebuilt version of this... if you can see the "m" branch.
I think it probably addresses some of these issues

**Comment by modderme123** [comment]
Number 2 & 3 are done
