### ISSUE TITLE
Switch player on Spectate doesnt work sometimes

### ISSUE THREAD

**Issue by deshah10** [daud-io/daud#130]
Random minor issue where `left mouse clicking` to switch players on spectate screen, doesnt work. No idea what causes this bug, as console log seemed fine. 

Currently the simple fix around it is to go back to main screen and click the `watch`  button or `escape` key, to spectate again.

**Comment by andylippitt** [comment]
this should be considered when someone debugs the final wormhole state @modderme123

**Comment by deshah10** [comment]
Ok cause of issue occurs when you die, the spectate screen on death, doesnt allow player switching
