### ISSUE TITLE
autofire and autoboost bugs

### ISSUE THREAD

**Issue by andylippitt** [daud-io/daud#24]
There are several related bugs in the input control system:
- boosting or firing while you die, leaves the action active. turns into autofire or autoboost after respawn
- clicking and dragging out of the window makes it miss the mouse-up, yielding autofire.

**Comment by modderme123** [comment]
Also something that causes autorespawn related to this

**Comment by deshah10** [comment]
Just idendified, Pressing `s` + `tab` causes an endless dashing **BUG**
