### ISSUE TITLE
Firefox slowdown

### ISSUE THREAD

**Issue by andylippitt** [daud-io/daud#41]
There have been reports of low FPS on firefox

Let's collect what we know about the issue here and see if we can solve it.

**Comment by andylippitt** [comment]
I've not been able to reproduce the issue in any meaningful way with the available machines I have. The only time I saw a significant difference in performance between chrome and firefox was while running over an RDP connection. I found that I was able to limit the bits of the code that were rendered and dramatically effect FPS, but it seemed to scale with how many canvas operations were taking place... an that sounds like an RDP artifact to me.

Possible workaround:
 - Restart Firefox in Safe Mode. If this fixes the problem, you may be able to revert to normal mode afterwords and retain the benefits

**Comment by andylippitt** [comment]
the dual layer alpha background was causing 60->30fps drop for some users
the alpha out-of-bounds area draw was dropping some clients to 7fps

**Comment by modderme123** [comment]
We might want to allow users to disable all alpha in settings

**Comment by andylippitt** [comment]
yes. I think I might have left it tied to the "fast" mode... but it should be a separate checkbox, default false, with a warning about perf

**Comment by modderme123** [comment]
Closing stale issue
