### ISSUE TITLE
planet transporters

### ISSUE THREAD

**Issue by modderme123** [daud-io/daud#66]
Have certain planets take fleets between worlds

**Comment by modderme123** [comment]
regular spawn locations. doesn't have to be near transporter

**Comment by andylippitt** [comment]
this is mostly a client-side effort
from the server, we'll add a "type" to messages. one of the types will be "join" with world coordinates (at the moment it's just a worldKey, but we should plan for a full server URL)

When the client sees one, it disconnects and reconnects.

Sound about right?

**Comment by andylippitt** [comment]
the solution should tee us up for auto-duels and lobby pledges

**Comment by modderme123** [comment]
I think a better solution would be to have the server switch the arena the client is in, and the client knows to do a partial refresh

**Comment by andylippitt** [comment]
that assumes that the world we're switching to is on the same server

**Comment by andylippitt** [comment]
see game.js line 195

this should be triggered upon touching the planet in the Wormhole Test world

```
            case "join":
                console.log('received join: ' + announcement.text());
                break;
```

**Comment by andylippitt** [comment]
there remains a bit of unresolved state after respawning in the new world. seems to be in dead/spectate mode
