### ISSUE TITLE
Improvements to death spectate screen

### ISSUE THREAD

**Issue by deshah10** [daud-io/daud#96]
- Have option to change nickname from the new death spectate screen while you wait for your respawn counter to renew.
- Simple useful tips to highlight how the player could survive/ improve, e.g.:

1. Use dash to quickly jump out of a scary situation 
2. Find and deploy shields to prevent getting shot.
3. Use missiles to target enemies from a far distance.
4. Combine dashig + shooting to surprise kill enemies.
5. etc...

**Comment by andylippitt** [comment]
Tips are done in the form of the spectate hints.

**Comment by andylippitt** [comment]
not sure we should do the nick thing, but seems like this one might be yours ;)
